trigger:
  branches:
    include:
      - main
pr:
  branches:
    include:
      - "*"
variables:
  TF_VERSION: "1.5.7"

stages:
  - stage: Validate
    jobs:
      - job: TerraformInitValidate
        pool:
          name: Default
        steps:
          - script: |
              Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi
              Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'
              displayName: 'Install Azure CLI (Windows)'
              shell: pwsh

          - script: |
              Invoke-WebRequest -Uri https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_windows_amd64.zip -OutFile terraform.zip
              Expand-Archive terraform.zip -DestinationPath $Env:USERPROFILE\bin
              $Env:PATH += ";$Env:USERPROFILE\bin"
              displayName: 'Install Terraform (Windows)'
              shell: pwsh

          - script: terraform init
            workingDirectory: environment
            displayName: "Terraform Init"

          - script: terraform validate
            workingDirectory: environment
            displayName: "Terraform Validate"

  - stage: Plan
    dependsOn: Validate
    condition: |
      or(
        eq(variables['Build.Reason'], 'PullRequest'),
        eq(variables['Build.SourceBranch'], 'refs/heads/main')
      )
    jobs:
      - job: TerraformPlan
        pool:
          name: Default
        steps:
          - script: terraform plan
            workingDirectory: environment
            displayName: "Terraform Plan"

  - stage: Apply
    dependsOn: Plan
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    jobs:
      - job: TerraformApply
        pool:
          name: Default
        steps:
          - script: terraform apply -auto-approve
            workingDirectory: environment
            displayName: "Terraform Apply"
